### PR TITLE
Check your dev env's

### PR DESCRIPTION
**Pull request by Shinkson47**
All review before closing

Checkout to `edb32f`, load in *intellij*, run gradle sync (Available from "Reload all projects" in the gradle window).

It should download and configure all libraries. After indexing and configuring, project should be runnable from `Desktop/DesktopLauncher`

Check:
 - [x] I can read / write to the repo
 - [x] I can run the demo project

If you recieve 'Unsupported class file major version 60', in the gradle window head to gradle settings, and change the gradle JVM to java 1.8.

### CODE REVIEW

**Review by d4nj2201 — APPROVED** [review]
All fine 👍

**Review by zeyneptugcekandirmaz — APPROVED** [review]

**Review by easmith181 — APPROVED** [review]
Works great

**Review by 77masterdawid77 — APPROVED** [review]
its good, everything work

**Review by itsPachou — APPROVED** [review]
Works great

**Review by d4nj2201 — COMMENTED** [review]
All good

**Pull request merged**
