### PR TITLE
Main menu, UI Skin & Credits.

### PR DESCRIPTION
**Pull request by Shinkson47**
> NB : Depends on #4. Merge #4 first.

# Adds menu screen
Fairly simple stage2d scene with a window and some buttons. All skinned with [Raeleus's Neon](https://ray3k.wordpress.com/neon-ui-skin-for-libgdx/)

Capture d’écran 2021-05-25 à 6 20 43 PM

# Credits
There's now a text file in the internal assets. It's contents are rendered to the credits screen letter by letter in a typewriter style animation.

https://user-images.githubusercontent.com/50697488/119541671-98196300-bd86-11eb-8aa0-d6df914a5930.mov

To alter credits, just edit the `assets/generic/credits.txt` file. The rendering logic will handle the rest.

I've added the license which covers us for use next to each asset in the credits :

Capture d’écran 2021-05-25 à 6 39 16 PM

### CODE REVIEW

**Comment by 77masterdawid77** [comment]
Look great 👍, I am having problems adding another branch to this commit so could you update licenses file for me? 

https://github.com/raeleus/skin-composer

https://helianthus-games.itch.io/parallax-space-background

I think those are the correct places you used the assets from.

**Comment by Shinkson47** [comment]
@77masterdawid77 Now that we have an easily maintainable credits screen, is it worth keeping track of licences separately still? Would it be good enough to write which license covers us next to each asset in the creditation?

**Comment by 77masterdawid77** [comment]
As long as we can find the sources later we can delete the licenses file and leave the credits as they are. I just want to make sure we can recheck all licenses before publishing our game.

Btw, Did you buy a 'Pixel art space backgrounds set' for 3 dollars? or did I find the wrong asset pack you used?

**Comment by Shinkson47** [comment]
Gotcha, and no - i wrote the wrong name, that's not the one i used. Corrected it in 1c41c96

**Review by 77masterdawid77 — APPROVED** [review]
Its well laid out and easy to follow. I understand everything enough to edit and add similar things that you have made. My utility.java file has some errors but I think ill be able to sort it out later. Great work, Hopefully other people start helping once the base program is fully made ;)

**Pull request merged**
